// Service worker: keeps the app shell available offline. Generated by
// tools/build.mjs from tools/sw.template.js; do not edit app/sw.js by hand.
const VERSION = 'ae1e2aa84339';
const SHELL = [
 "./",
 "./config/exam.json",
 "./css/app.css",
 "./data/topics.json",
 "./fonts/atkinson-hyperlegible-next-latin-400-italic.woff2",
 "./fonts/atkinson-hyperlegible-next-latin-400-normal.woff2",
 "./fonts/atkinson-hyperlegible-next-latin-700-normal.woff2",
 "./fonts/bricolage-grotesque-latin-600-normal.woff2",
 "./fonts/bricolage-grotesque-latin-800-normal.woff2",
 "./fonts/ibm-plex-mono-latin-500-normal.woff2",
 "./icons/apple-touch-icon.png",
 "./icons/icon-192.png",
 "./icons/icon-512.png",
 "./icons/icon-maskable-512.png",
 "./index.html",
 "./js/backup.js",
 "./js/charts.js",
 "./js/db.js",
 "./js/feedback.js",
 "./js/lock.js",
 "./js/main.js",
 "./js/md.js",
 "./js/pack.js",
 "./js/progress.js",
 "./js/results.js",
 "./js/sit.js",
 "./js/util.js",
 "./manifest.webmanifest",
 "./vendor/jszip.min.js",
 "./vendor/katex/fonts/KaTeX_AMS-Regular.woff2",
 "./vendor/katex/fonts/KaTeX_Caligraphic-Bold.woff2",
 "./vendor/katex/fonts/KaTeX_Caligraphic-Regular.woff2",
 "./vendor/katex/fonts/KaTeX_Fraktur-Bold.woff2",
 "./vendor/katex/fonts/KaTeX_Fraktur-Regular.woff2",
 "./vendor/katex/fonts/KaTeX_Main-Bold.woff2",
 "./vendor/katex/fonts/KaTeX_Main-BoldItalic.woff2",
 "./vendor/katex/fonts/KaTeX_Main-Italic.woff2",
 "./vendor/katex/fonts/KaTeX_Main-Regular.woff2",
 "./vendor/katex/fonts/KaTeX_Math-BoldItalic.woff2",
 "./vendor/katex/fonts/KaTeX_Math-Italic.woff2",
 "./vendor/katex/fonts/KaTeX_SansSerif-Bold.woff2",
 "./vendor/katex/fonts/KaTeX_SansSerif-Italic.woff2",
 "./vendor/katex/fonts/KaTeX_SansSerif-Regular.woff2",
 "./vendor/katex/fonts/KaTeX_Script-Regular.woff2",
 "./vendor/katex/fonts/KaTeX_Size1-Regular.woff2",
 "./vendor/katex/fonts/KaTeX_Size2-Regular.woff2",
 "./vendor/katex/fonts/KaTeX_Size3-Regular.woff2",
 "./vendor/katex/fonts/KaTeX_Size4-Regular.woff2",
 "./vendor/katex/fonts/KaTeX_Typewriter-Regular.woff2",
 "./vendor/katex/katex.min.css",
 "./vendor/katex/katex.min.js",
 "./vendor/marked.esm.js",
 "./js/build-info.js",
 "./library/index.json"
];
const SHELL_CACHE = `shell-${VERSION}`;
const LIB_CACHE = 'library-v1';

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(SHELL_CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k.startsWith('shell-') && k !== SHELL_CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== self.location.origin) return;
  const path = url.pathname;
  // Encrypted library papers: cache forever once downloaded (file names change when content does).
  if (path.includes('/library/') && path.endsWith('.bin')) {
    e.respondWith((async () => {
      const cache = await caches.open(LIB_CACHE);
      const hit = await cache.match(e.request);
      if (hit) return hit;
      const res = await fetch(e.request);
      if (res.ok) cache.put(e.request, res.clone());
      return res;
    })());
    return;
  }
  // Data that can change between deploys: network first, cache fallback.
  if (path.endsWith('/library/index.json') || path.endsWith('/config/exam.json')) {
    e.respondWith((async () => {
      const cache = await caches.open(SHELL_CACHE);
      try {
        const res = await fetch(e.request, { cache: 'no-cache' });
        if (res.ok) cache.put(e.request, res.clone());
        return res;
      } catch {
        return (await cache.match(e.request, { ignoreSearch: true })) || Response.error();
      }
    })());
    return;
  }
  // App shell: cache first.
  e.respondWith((async () => {
    const hit = await caches.match(e.request, { ignoreSearch: true });
    if (hit) return hit;
    try {
      return await fetch(e.request);
    } catch {
      if (e.request.mode === 'navigate') return (await caches.match('./index.html')) || Response.error();
      return Response.error();
    }
  })());
});
